name = "Plasm"
uuid = "92146e7c-85be-4b32-b127-a84d188ef73a"
authors = ["Giorgio Scorzelli"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
