export WHITE,RED,GREEN,BLUE,CYAN,MAGENTA,YELLOW,ORANGE,PURPLE,BROWN,GRAY,BLACK, TRANSPARENT
export DEFAULT_SHOW_AXIS,DEFAULT_BACKGROUND_COLOR,DEFAULT_LAR_BACKGROUND_COLOR, DEFAULT_SHOW_LINES,DEFAULT_USE_ORTHO, DEFAULT_FOV
export DEFAULT_POINT_SIZE,DEFAULT_POINT_COLOR
export DEFAULT_SHOW_LINES,DEFAULT_LINE_WIDTH,DEFAULT_LINE_COLOR
export DEFAULT_FACE_COLOR
export DEFAULT_LIGHTING_ENABLED
export DEFAULT_TEXT_V_COLOR,DEFAULT_TEXT_EV_COLOR,DEFAULT_TEXT_FV_COLOR
export DEFAULT_V_FONTSIZE,DEFAULT_EV_FONTSIZE,DEFAULT_FV_FONTSIZE
export DEFAULT_TEXT_SCALING

const WHITE       = Point4d([1.0, 1.0, 1.0, 1.0])
const RED         = Point4d([1.0, 0.0, 0.0, 1.0])
const GREEN       = Point4d([0.0, 1.0, 0.0, 1.0])
const BLUE        = Point4d([0.0, 0.0, 1.0, 1.0])
const CYAN        = Point4d([0.0, 1.0, 1.0, 1.0])
const MAGENTA     = Point4d([1.0, 0.0, 1.0, 1.0])
const YELLOW      = Point4d([1.0, 1.0, 0.0, 1.0])
const ORANGE      = Point4d([1.0, 0.65, 1.0, 1.0])
const PURPLE      = Point4d([0.5, 0.0, 0.5, 1.0])
const BROWN       = Point4d([0.65, 0.16, 0.16, 1.0])
const GRAY        = Point4d([0.5, 0.5, 0.5, 1.0])
const BLACK       = Point4d([0.0, 0.0, 0.0, 1.0])
const DARK_GRAY   = Point4d(0.3,0.3,0.3,1.0)
const LIGHT_GRAY  = Point4d(0.8,0.8,0.8,1.0)
const TRANSPARENT = Point4d([0.0,0.0,0.0,0.0])

DEFAULT_BACKGROUND_COLOR= Point4d([0.3,0.4,0.5,1.0]) 
DEFAULT_LAR_BACKGROUND_COLOR=WHITE

DEFAULT_USE_ORTHO=true
DEFAULT_SHOW_LINES=true
DEFAULT_SHOW_AXIS=true
DEFAULT_FOV=60.0
DEFAULT_LIGHTING_ENABLED=false

DEFAULT_POINT_SIZE   = 1
DEFAULT_LINE_WIDTH   = 2
DEFAULT_POINT_COLOR  = WHITE
DEFAULT_LINE_COLOR   = DARK_GRAY
DEFAULT_FACE_COLOR   = LIGHT_GRAY

DEFAULT_TEXT_V_COLOR  = BLACK  
DEFAULT_TEXT_EV_COLOR = CYAN
DEFAULT_TEXT_FV_COLOR = RED

DEFAULT_V_FONTSIZE =0.04
DEFAULT_EV_FONTSIZE=0.06
DEFAULT_FV_FONTSIZE=0.08

DEFAULT_TEXT_SCALING=(0.250,0.375)


